version: "3.8"
services:
  network-ids:
    build: .
    image: network-ids-app:local
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_ENTRYPOINT=app/realtime_detector1.py
    volumes:
<<<<<<< HEAD
      - ./models:/app/models   # mount models
      - ./data:/app/data       # â† ADD THIS to persist database
=======
      - ./models:/app/models   # mount local models into container
>>>>>>> 324e6b131986dd4b324dabf721cc8a689dbe3715
    restart: unless-stopped
